### ISSUE TITLE
show assignee in sub-issues section

### ISSUE THREAD

**Issue by lucacioria** [buildo/nemobot#95]
## requirements
- be able to quickly see the assignee of each sub-issue from the macro issue

## specs
show as:
- [x] implement cool new feature component #1234 **[assignee]**

**Comment by FrancescoCioria** [comment]
👍 (also very easy to implement)

**Comment by gabro** [comment]
👍 

Along the same lines, show the `in review`/`wip` status

- [ ] implement cool new feature component #1233 **[lucacioria]** *WIP*
- [ ] implement second new feature component #1234 **[lucacioria]** *WIP*
- [ ] implement third feature component #1235 **[lucacioria]** *in review*
- [x] <s>implement fourth feature component #1236 **[lucacioria]**</s>

**Comment by lucacioria** [comment]
@FrancescoCioria do you think we can do this this week? It's useful when I review macro issues in my LOL QualityAssurance :)
